---
title: "Phonological Networks and Systematicity in Early Lexical Acquisition"
---

## Set up

```{r setup, include=FALSE}

source("prelims.R")
r_refs(file="r-references.bib")

my_citations <- cite_r(
  file="r-references.bib"
  , pkgs=c("tidyverse", "igraph", "papaja", "lmerTest")
  , withhold=FALSE
  , footnote=TRUE
)

# load files

globalthresholds_AOP_lyon <- feather::read_feather("Data/globalthresholds_AOP_lyon.feather") %>% 
  filter(threshold == 0.25) 
globalthresholds_AOP_providence <- feather::read_feather("Data/globalthresholds_AOP_providence.feather") %>% 
  filter(threshold == 0.25)
globalthresholds_AOP <- rbind(globalthresholds_AOP_lyon, globalthresholds_AOP_providence)

full_lyon <- feather::read_feather("Data/globalthresholds_AOP_lyon.feather") %>% 
  filter(threshold == .99)
full_providence <- feather::read_feather("Data/globalthresholds_AOP_providence.feather") %>% 
  filter(threshold == .99)
full_thresholds <- rbind(full_lyon, full_providence)

regression_data_lyon <- feather::read_feather("Data/regression_data_lyon.feather")
regression_data_providence <- feather::read_feather("Data/regression_data_providence.feather")
regression_data <- rbind(regression_data_lyon, regression_data_providence)

regression_data$category = relevel(regression_data$category, ref="object_word")

comparison_data_P <- read_csv("Data/comparison_data_providence.csv")                                                            
comparison_data_L <- read_csv("Data/comparison_data_lyon.csv")
comparison_data <- rbind(comparison_data_P, comparison_data_L)

source("PhonologicalNetworks-Figures.R")
source("PhonologicalNetworks-Tables.R")

stat_sum_df <- function(fun, geom="crossbar", ...) {
  stat_summary(fun.data=fun, colour="red", geom=geom, width=0.2, ...)
}

```

## Methods

```{r data overview}
types.corpus <- regression_data %>%
  group_by(corpus, Speaker) %>%
  distinct(gloss1, .keep_all=T) %>%
  tally() %>% summarise(n=sum(n))

types <- regression_data %>%
  group_by(Speaker) %>%
  distinct(gloss1, .keep_all=T) %>%
  tally() %>% summarise(n=sum(n))

tokens <- regression_data %>%
  summarise(mean_tok=mean(n_tokens),
            sd_tok = sd(n_tokens))

syls <- comparison_data %>%
  distinct(Gloss, Speaker, .keep_all = T) %>%
  group_by(corpus) %>% 
  summarise(mean_syl = mean(nsyl_target),
              sd_syl = sd(nsyl_target),
              max_syl = max(nsyl_target))

nsyls <- comparison_data %>%
    distinct(Gloss, Speaker, .keep_all = T) %>%
  group_by(corpus, nsyl_target) %>%
  tally() %>%
  pivot_wider(names_from = corpus, values_from = n)

syl.4 <- subset(nsyls, nsyl_target == 4)$French
```

```{r table-data-overview, echo=F, message=FALSE, warning=FALSE, comment=F}
cap="Age (months) at first session, number of sessions and number of distinct word types produced by each child in the dataset. Means and SDs for each corpus are shown in bold."

kable(table.data.overview, "latex", booktabs=T, longtable=T, 
      caption=cap, digits=0, align="c")  %>%  # might need to turn digits back to 0
  kable_styling()%>%
  row_spec(4, bold=F, hline_after=T) %>%
  row_spec(5, bold=T, hline_after=F) %>%
  row_spec(6, bold=T, hline_after=T) %>%
  row_spec(11, bold=F,hline_after=T) %>%
  row_spec(12, bold=T,hline_after=F) %>%
  row_spec(13, bold=T,hline_after=T) %>%  
  row_spec(14, bold=T,hline_after=F) %>%
  row_spec(15, bold=T,hline_after=F)
```


```{r network comparison}

ntargetactual <- globalthresholds_AOP %>% group_by(data_type) %>% tally()
network_diff <- nrow(full_thresholds) - nrow(globalthresholds_AOP)

```

## Results

### Age of production (AoP) ~ connectivity

```{r aop-degree correlations, message=FALSE, warning=FALSE, include=FALSE}

stats.corr.all <- table.aop.deg.corr.speaker %>% summarise(mean_rho=mean(rho),
                                                      sd_rho=sd(rho))

stats.corr_Providence <- globalthresholds_AOP %>%
        group_by(Speaker, corpus) %>%
        summarize(rho=stats::cor.test(AOP, degree, method="sp")$estimate,
                  pval=stats::cor.test(AOP, degree, method="sp")$p.value
                  ) %>%
        ungroup() %>% group_by(corpus) %>%
  summarise(mean_rho=mean(rho),
            sd_rho=sd(rho)) %>%
  filter(corpus == "English")

stats.corr_Lyon <- globalthresholds_AOP %>%
        group_by(Speaker, corpus) %>%
        summarize(rho=stats::cor.test(AOP, degree, method="sp")$estimate,
                  pval=stats::cor.test(AOP, degree, method="sp")$p.value
                  ) %>%
        ungroup() %>% group_by(corpus) %>%
  summarise(mean_rho=mean(rho),
            sd_rho=sd(rho)) %>%
  filter(corpus == "French")

```

### Network growth models

```{r regression model actual, message=FALSE, warning=FALSE, include=FALSE}

reg_dat <- regression_data[which(complete.cases(regression_data[,c('PAQ_scaled_target', 'PAT_scaled', 'length_scaled', 'freq_scaled', 'age_scaled', 'corpus')])),]

model0_A <- glmer(learned_next ~
                    length_scaled*age_scaled +
                    tokens_scaled*age_scaled +
                    freq_scaled*age_scaled +
                    vocab_scaled*age_scaled +
                    corpus +
                    category +
                    (1+age_scaled|Speaker),
                    family=binomial("logit"),
                    control=glmerControl(calc.derivs=FALSE,
                                         optimizer="bobyqa",
                                           # specifiying optimizer to support convergence (does not converge without this)
                                         optCtrl=list(maxfun=2e5)),
                    data=subset(reg_dat, data_type == "actual"))

model1_A <- glmer(learned_next ~
                  length_scaled*age_scaled +
                    tokens_scaled*age_scaled +
                  freq_scaled*age_scaled +
                    vocab_scaled*age_scaled +
                   corpus +
                    category +
                    PAT_scaled*age_scaled +
                    (1+age_scaled|Speaker), 
                    family=binomial("logit"),
                    control=glmerControl(calc.derivs=FALSE,
                                         optimizer="bobyqa",
                                         optCtrl=list(maxfun=2e5)),
                    data=subset(reg_dat, data_type == "actual"))

model2_A <- glmer(learned_next ~
                  length_scaled*age_scaled +
                    tokens_scaled*age_scaled +
                  freq_scaled*age_scaled +
                    vocab_scaled*age_scaled +
                    corpus +
                    category +
                    PAQ_scaled_target*age_scaled +
                    (1+age_scaled|Speaker),
                    family=binomial("logit"),
                    control=glmerControl(calc.derivs=FALSE,
                                         optimizer="bobyqa",
                                         optCtrl=list(maxfun=2e5)),
                    data=subset(reg_dat, data_type == "actual"))


models01_A <- anova(model0_A, model1_A)
models02_A <- anova(model0_A, model2_A)

model3_A <- glmer(learned_next ~
                    length_scaled*age_scaled +
                    tokens_scaled*age_scaled +
                      freq_scaled*age_scaled +
                    vocab_scaled*age_scaled +
                    corpus +
                    category +
                    PAQ_scaled_target*age_scaled +
                      PAT_scaled*age_scaled +
                    (1+age_scaled|Speaker),
                    family=binomial("logit"),
                    control=glmerControl(calc.derivs=FALSE,
                                         optimizer="bobyqa",
                                         optCtrl=list(maxfun=2e5)),
                    data=subset(reg_dat, data_type == "actual"))

models13_A <- anova(model1_A, model3_A)
models23_A <- anova(model2_A, model3_A)

#summary(model3_A)

table.A.model.output <- rbind(models01_A, models02_A, models13_A, models23_A) %>%
  rownames_to_column(var="Model") %>%
  filter(Chisq > 0) %>%
  rename("p"=`Pr(>Chisq)`) %>%
  mutate(Model=fct_recode(Model,
                           "null vs. PAT"="model1_A",
                            "null vs. PAQ"="model2_A",
                            "PAT vs. PAT+PAQ"="model3_A",
                            "PAQ vs. PAT+PAQ"="model3_A1"),
             p=scales::pvalue(p)
        ) %>%
  select(Model, `Df`, `Chisq`, `p`)

model.summary_A <- summary(model3_A)

model3_A_tab <- model.summary_A$coefficients %>%
  as.data.frame %>%
  rename(
    "b"="Estimate"
     , "SE"="Std. Error"
     , "z"="z value"
     , "p"="Pr(>|z|)") %>%
  mutate(
    Effect=papaja:::beautify_terms(rownames(.))
  )

table.model3_A <- model3_A_tab %>%
  printnum(
    digits=c(2, 2, 2, 3)
    , gt1=c(TRUE, TRUE, TRUE, TRUE)
    , zero=c(TRUE, TRUE, TRUE, TRUE)
  ) %>%
  select(Effect, `b`, `SE`, `z`, `p`) %>%
  rename("beta"=`b`) %>%
  mutate(beta=as.numeric(beta),
        SE=as.numeric(SE),
        `z`=as.numeric(`z`),
        `p`=as.numeric(`p`),
             p=scales::pvalue(p))
```
```{r regression model Target, message=FALSE, warning=FALSE, include=FALSE}

model0_T <- glmer(learned_next ~
                    length_scaled*age_scaled +
                    tokens_scaled*age_scaled +
                  freq_scaled*age_scaled +
                    vocab_scaled*age_scaled +
                   corpus +
                    category +
                    (1+age_scaled|Speaker), 
                    family=binomial("logit"),
                    control=glmerControl(calc.derivs=FALSE,
                                         optimizer="bobyqa",
                                         optCtrl=list(maxfun=2e5)),
                    data=subset(reg_dat, data_type == "target"))



model1_T <- glmer(learned_next ~
                  length_scaled*age_scaled +
                  tokens_scaled*age_scaled +
                  freq_scaled*age_scaled +
                    vocab_scaled*age_scaled +
                  corpus +
                  category +
                  PAT_scaled*age_scaled +
                  (1+age_scaled|Speaker),
                  family=binomial("logit"),
                  control=glmerControl(calc.derivs=FALSE,
                                         optimizer="bobyqa",
                                         optCtrl=list(maxfun=2e5)),
                    data=subset(reg_dat, data_type == "target"))

model2_T <- glmer(learned_next ~
                  length_scaled*age_scaled +
                  tokens_scaled*age_scaled +
                  freq_scaled*age_scaled +
                    vocab_scaled*age_scaled +
                  corpus +
                  category +
                  PAQ_scaled_target*age_scaled +
                  (1+age_scaled|Speaker),
                  family=binomial("logit"),
                  control=glmerControl(calc.derivs=FALSE,
                                         optimizer="bobyqa",
                                         optCtrl=list(maxfun=2e5)),
                  data=subset(reg_dat, data_type == "target"))


models01_T <- anova(model0_T, model1_T)
models02_T <- anova(model0_T, model2_T)

model3_T <- glmer(learned_next ~
                  length_scaled*age_scaled +
                  tokens_scaled*age_scaled +
                  freq_scaled*age_scaled +
                    vocab_scaled*age_scaled +
                  corpus +
                  category +
                  PAQ_scaled_target*age_scaled +
                  PAT_scaled*age_scaled +
                  (1+age_scaled|Speaker),
                    family=binomial("logit"),
                    control=glmerControl(calc.derivs=FALSE,
                                         optimizer="bobyqa",
                                         optCtrl=list(maxfun=2e5)),
                    data=subset(reg_dat, data_type == "target"))

models13_T <- anova(model1_T, model3_T)
models23_T <- anova(model2_T, model3_T)

#summary(model3_T)

table.T.model.output <- rbind(models01_T, models02_T, models13_T, models23_T) %>%
  rownames_to_column(var="Model") %>%
  filter(Chisq > 0) %>%
  rename("p"=`Pr(>Chisq)`) %>%
  mutate(p=scales::pvalue(p)
         ) %>%
  select(`Df`, `Chisq`, `p`)

table.model.outputs <- cbind(table.A.model.output, table.T.model.output)

model.summary_T <- summary(model3_T)

model3_T_tab <- model.summary_T$coefficients %>%
  as.data.frame %>%
  rename(
    "b"="Estimate"
     , "SE"="Std. Error"
     , "z"="z value"
     , "p"="Pr(>|z|)") %>%
  mutate(
    Effect=papaja:::beautify_terms(rownames(.))
  )

table.model3_T <- model3_T_tab %>%
  printnum(
    digits=c(2, 2, 2, 3)
    , gt1=c(TRUE, TRUE, TRUE, TRUE)
    , zero=c(TRUE, TRUE, TRUE, TRUE)
  ) %>%
  select(Effect, `b`, `SE`, `z`, `p`) %>%
  rename("beta"=`b`) %>%
  mutate(beta=as.numeric(beta),
        SE=as.numeric(SE),
        `z`=as.numeric(`z`),
        `p`=as.numeric(`p`),
             p=scales::pvalue(p))

rownames(table.model3_T) <- NULL

table.model.3 <- cbind(table.model3_A, table.model3_T)
table.model.summary <- table.model.3[,-6]

table.model.summary <- table.model.summary %>% mutate(Effect=fct_recode(Effect,
                                               Age="Age scaled",
                                               Length="Length scaled",
                                               `n Tokens` = "Tokens scaled",
                                              `Word frequency`="Freq scaled",
                                              `Vocab size` = "Vocab scaled",
                                              `Corpus` = "CorpusFrench",
                                              `PAQ value`="PAQ scaled target",
                                              `PAT value`="PAT scaled",
                                              `Age x Length`="Length scaled $\\times$ Age scaled",
                                              `Age x n Tokens` = "Age scaled $\\times$ Tokens scaled",
                                              `Age x Frequency`="Age scaled $\\times$ Freq scaled",
                                              `Age x Vocab size`="Age scaled $\\times$ Vocab scaled",
                                              `Age x PAQ`="Age scaled $\\times$ PAQ scaled target",
                                              `Age x PAT`="Age scaled $\\times$ PAT scaled")) %>%
  filter(!(grepl("Category", Effect, ignore.case = TRUE)))

rownames(table.model.summary) <- NULL
  

actual_beta_PAT <- subset(model3_A_tab, Effect == "PAT scaled")$b
actual_beta_PAQ <- subset(model3_A_tab, Effect == "PAQ scaled target")$b
actual_p_PAT <- subset(model3_A_tab, Effect == "PAT scaled")$p
actual_p_PAQ <- subset(model3_A_tab, Effect == "PAQ scaled target")$p

target_beta_PAT <- subset(model3_T_tab, Effect == "PAT scaled")$b
target_beta_PAQ <- subset(model3_T_tab, Effect == "PAQ scaled target")$b
target_p_PAT <- subset(model3_T_tab, Effect == "PAT scaled")$p
target_p_PAQ <- subset(model3_T_tab, Effect == "PAQ scaled target")$p

```

```{r table-model-outputs, echo=FALSE, message=FALSE, warning=FALSE}
cap="Outputs from nested model comparisons comparing logistic regression models predicting acquisition of words in each month according to PAT- and PAQ-like growth structures."
kable(table.model.outputs, "latex", booktabs=T, longtable=T, caption=cap, digits=2, align="c",
      col.names=c("Model", "Df", "Chi Sq", "p", "Df", "Chi Sq", "p")) %>%
    kable_styling()%>%
  add_header_above(c(" "=1, "Actual"=3, "Target"=3)) %>%
  row_spec(4, hline_after=T)
```

```{r table-data-summary, echo=F, message=FALSE, warning=FALSE, comment=F}
cap="Results from maximal logistic regression model (model 3) testing the effects of network growth values, corpus (English as baseline), word frequency, vocabulary size, word category, n tokens and word length to predict word acquisition. All variables were scaled and centred. Category has been removed for ease of interpretation but is shown in the full model output in S2."
knitr::kable(table.model.summary, "latex", booktabs=T, longtable=T, caption=cap, digits=2, align="c",
          col.names=gsub("[.1]", "", names(table.model.summary))) %>%
  add_header_above(c(" "=1, "Actual"=4, "Target"=4))
```

### PAT-like growth over time

```{r GAMM prep, echo=F, message=FALSE, warning=FALSE, comment=F}

reg_data <- subset(regression_data, age == (AOP-1))

reg_dat_actual <- subset(reg_data, data_type == "actual")
reg_dat_target <- subset(reg_data, data_type == "target")

reg_dat_actual$start.event <- reg_dat_actual$session_ordinal == 1 
reg_dat_target$start.event <- reg_dat_target$session_ordinal == 1 

```


```{r GAMM age actual PAT, message=FALSE, warning=FALSE, include=FALSE}

PAT.gamm.base_A <- bam(PAT_scaled ~ 
                       corpus +
                       category +
                       s(freq_scaled, bs = "cr") + 
                       s(length_scaled, bs = "cr") +
                       s(tokens_scaled, bs = "cr") + 
                       s(vocab_scaled, bs = "cr") +
                       s(PAQ_target, bs = "cr") +
                       s(AOP, bs = "cr") +                       
                       ti(AOP, PAQ_target) +
                       ti(AOP, freq_scaled) + 
                       ti(AOP, length_scaled) +
                       ti(AOP, tokens_scaled) +
                       ti(AOP, vocab_scaled) +
                       s(AOP, by=Speaker, bs="cr") +
                       s(AOP, by=corpus, bs="cr"),
                     dat=reg_dat_actual, method="ML")

rA <- start_value_rho(PAT.gamm.base_A) 

PAT.gamm.1_A <- bam(PAT_scaled ~ 
                      corpus +
                      category +
                      s(freq_scaled, bs = "cr") + 
                      s(length_scaled, bs = "cr") +
                      s(tokens_scaled, bs = "cr") + 
                      s(vocab_scaled, bs = "cr") +
                       s(PAQ_target, bs = "cr") +
                       s(AOP, bs = "cr") +                       
                       ti(AOP, PAQ_target) +
                       ti(AOP, freq_scaled) + 
                       ti(AOP, length_scaled) +
                       ti(AOP, tokens_scaled) +
                         ti(AOP, vocab_scaled) +
                      s(AOP, corpus, bs="fs", m=1, k=2) +
                      s(AOP, Speaker, bs="fs", m=1, k=9),  
                        data = reg_dat_actual, method = "ML", 
                        rho=rA, AR.start=reg_dat_actual$start.event)

PAT.gamm.0_A <- bam(PAT_scaled ~ 
                      corpus +
                      category +
                      s(freq_scaled, bs = "cr") + 
                      s(length_scaled, bs = "cr") +
                      s(tokens_scaled, bs = "cr") + 
                      s(vocab_scaled, bs = "cr") +
                      s(PAQ_target, bs = "cr") +
                       # s(AOP, bs = "cr") +                       
                       # ti(AOP, PAQ_target) +
                       # ti(AOP, freq_scaled) + 
                       # ti(AOP, length_scaled) +
                       # ti(AOP, tokens_scaled) +
                       # ti(AOP, vocab_scaled) +
                      s(AOP, corpus, bs="fs", m=1, k=2) +
                      s(AOP, Speaker, bs="fs", m=1, k=9),  
                    data = reg_dat_actual, method = "ML", 
                    rho=rA, AR.start=reg_dat_actual$start.event)

PAT.gamm.actual <- compareML(PAT.gamm.1_A, PAT.gamm.0_A)
PAT.gamm.A <- PAT.gamm.actual$table

PAT.gamm.A_summ <- summary(PAT.gamm.1_A)

```

```{r GAMM age target PAT, message=FALSE, warning=FALSE, include=FALSE}

PAT.gamm.base_T <- bam(PAT_scaled ~ 
                       corpus +
                       category +
                       s(freq_scaled, bs = "cr") + 
                       s(length_scaled, bs = "cr") +
                       s(tokens_scaled, bs = "cr") + 
                       s(vocab_scaled, bs = "cr") +
                       s(PAQ_target, bs = "cr") +
                       s(AOP, bs = "cr") +                       
                       ti(AOP, PAQ_target) +
                       ti(AOP, freq_scaled) + 
                       ti(AOP, length_scaled) +
                       ti(AOP, tokens_scaled) +
                       ti(AOP, vocab_scaled) +
                       s(AOP, by=Speaker, bs="cr") +
                       s(AOP, by=corpus, bs="cr"),
                     dat=reg_dat_target, method="ML")

rT <- start_value_rho(PAT.gamm.base_T) 

PAT.gamm.1_T <- bam(PAT_scaled ~ 
                      corpus +
                      category +
                      s(freq_scaled, bs = "cr") + 
                      s(length_scaled, bs = "cr") +
                      s(tokens_scaled, bs = "cr") + 
                      s(vocab_scaled, bs = "cr") +
                       s(PAQ_target, bs = "cr") +
                       s(AOP, bs = "cr") +                       
                       ti(AOP, PAQ_target) +
                       ti(AOP, freq_scaled) + 
                       ti(AOP, length_scaled) +
                       ti(AOP, tokens_scaled) +
                         ti(AOP, vocab_scaled) +
                      s(AOP, corpus, bs="fs", m=1, k=2) +
                      s(AOP, Speaker, bs="fs", m=1, k=9),  
                        data = reg_dat_target, method = "ML", 
                        rho=rT, AR.start=reg_dat_target$start.event)

PAT.gamm.0_T <- bam(PAT_scaled ~ 
                      corpus +
                      category +
                      s(freq_scaled, bs = "cr") + 
                      s(length_scaled, bs = "cr") +
                      s(tokens_scaled, bs = "cr") + 
                      s(vocab_scaled, bs = "cr") +
                       s(PAQ_target, bs = "cr") +
                       # s(AOP, bs = "cr") +                       
                       # ti(AOP, PAQ_target) +
                       # ti(AOP, freq_scaled) + 
                       # ti(AOP, length_scaled) +
                       # ti(AOP, tokens_scaled) +
                       #   ti(AOP, vocab_scaled) +
                      s(AOP, corpus, bs="fs", m=1, k=2) +
                      s(AOP, Speaker, bs="fs", m=1, k=9),  
                    data = reg_dat_target, method = "ML", 
                    rho=rT, AR.start=reg_dat_target$start.event)

PAT.gamm.target <- compareML(PAT.gamm.1_T, PAT.gamm.0_T)
PAT.gamm.T <- PAT.gamm.target$table

PAT.gamm.A.summ <- summary(PAT.gamm.1_A)
PAT.gamm.T.summ <- summary(PAT.gamm.1_T)

```

```{r GAMM age actual PAQ, message=FALSE, warning=FALSE, include=FALSE}

PAQ.gamm.base_A <- bam(PAQ_scaled_target ~ 
                       corpus +
                       category +
                       s(freq_scaled, bs = "cr") + 
                       s(length_scaled, bs = "cr") +
                       s(tokens_scaled, bs = "cr") + 
                       s(vocab_scaled, bs = "cr") +
                       s(PAT_scaled, bs = "cr") +
                       s(AOP, bs = "cr") +                       
                       ti(AOP, PAT_scaled) +
                       ti(AOP, freq_scaled) + 
                       ti(AOP, length_scaled) +
                       ti(AOP, tokens_scaled) +
                       ti(AOP, vocab_scaled) +
                       s(AOP, by=Speaker, bs="cr") +
                       s(AOP, by=corpus, bs="cr"),
                     dat=reg_dat_actual, method="ML")

rA <- start_value_rho(PAT.gamm.base_A) 

PAQ.gamm.1_A <- bam(PAQ_scaled_target ~ 
                      corpus +
                      category +
                      s(freq_scaled, bs = "cr") + 
                      s(length_scaled, bs = "cr") +
                      s(tokens_scaled, bs = "cr") + 
                      s(vocab_scaled, bs = "cr") +
                       s(PAT_scaled, bs = "cr") +
                       s(AOP, bs = "cr") +                       
                       ti(AOP, PAT_scaled) +
                       ti(AOP, freq_scaled) + 
                       ti(AOP, length_scaled) +
                       ti(AOP, tokens_scaled) +
                         ti(AOP, vocab_scaled) +
                      s(AOP, corpus, bs="fs", m=1, k=2) +
                      s(AOP, Speaker, bs="fs", m=1, k=9),  
                        data = reg_dat_actual, method = "ML", 
                        rho=rA, AR.start=reg_dat_actual$start.event)

PAQ.gamm.0_A <- bam(PAQ_scaled_target ~ 
                      corpus +
                      category +
                      s(freq_scaled, bs = "cr") + 
                      s(length_scaled, bs = "cr") +
                      s(tokens_scaled, bs = "cr") + 
                      s(vocab_scaled, bs = "cr") +
                       s(PAT_scaled, bs = "cr") +
                       # s(AOP, bs = "cr") +                       
                       # ti(AOP, PAT_scaled) +
                       # ti(AOP, freq_scaled) + 
                       # ti(AOP, length_scaled) +
                       # ti(AOP, tokens_scaled) +
                       #   ti(AOP, vocab_scaled) +
                      s(AOP, corpus, bs="fs", m=1, k=2) +
                      s(AOP, Speaker, bs="fs", m=1, k=9),   
                    data = reg_dat_actual, method = "ML", 
                    rho=rA, AR.start=reg_dat_actual$start.event)

PAQ.gamm.actual <- compareML(PAQ.gamm.1_A, PAQ.gamm.0_A)
PAQ.gamm.A <- PAQ.gamm.actual$table
PAQ.gamm.A_summ <- summary(PAQ.gamm.1_A)

```

```{r GAMM age target PAQ, message=FALSE, warning=FALSE, include=FALSE}

PAQ.gamm.base_T <- bam(PAQ_scaled_target ~ 
                       corpus +
                       category +
                       s(freq_scaled, bs = "cr") + 
                       s(length_scaled, bs = "cr") +
                       s(tokens_scaled, bs = "cr") + 
                       s(vocab_scaled, bs = "cr") +
                       s(PAT_scaled, bs = "cr") +
                       s(AOP, bs = "cr") +                       
                       ti(AOP, PAT_scaled) +
                       ti(AOP, freq_scaled) + 
                       ti(AOP, length_scaled) +
                       ti(AOP, tokens_scaled) +
                       ti(AOP, vocab_scaled) +
                       s(AOP, by=Speaker, bs="cr") +
                       s(AOP, by=corpus, bs="cr"),
                     dat=reg_dat_target, method="ML")

rT <- start_value_rho(PAT.gamm.base_T) 

PAQ.gamm.1_T <- bam(PAQ_scaled_target ~ 
                      corpus +
                      category +
                      s(freq_scaled, bs = "cr") + 
                      s(length_scaled, bs = "cr") +
                      s(tokens_scaled, bs = "cr") + 
                      s(vocab_scaled, bs = "cr") +
                       s(PAT_scaled, bs = "cr") +
                       s(AOP, bs = "cr") +                       
                       ti(AOP, PAT_scaled) +
                       ti(AOP, freq_scaled) + 
                       ti(AOP, length_scaled) +
                       ti(AOP, tokens_scaled) +
                         ti(AOP, vocab_scaled) +
                      s(AOP, corpus, bs="fs", m=1, k=2) +
                      s(AOP, Speaker, bs="fs", m=1, k=9), 
                        data = reg_dat_target, method = "ML", 
                        rho=rA, AR.start=reg_dat_target$start.event)

PAQ.gamm.0_T <- bam(PAQ_scaled_target ~ 
                      corpus +
                      category +
                      s(freq_scaled, bs = "cr") + 
                      s(length_scaled, bs = "cr") +
                      s(tokens_scaled, bs = "cr") + 
                      s(vocab_scaled, bs = "cr") +
                       s(PAT_scaled, bs = "cr") +
                       # s(AOP, bs = "cr") +                       
                       # ti(AOP, PAT_scaled) +
                       # ti(AOP, freq_scaled) + 
                       # ti(AOP, length_scaled) +
                       # ti(AOP, tokens_scaled) +
                       #   ti(AOP, vocab_scaled) +
                      s(AOP, corpus, bs="fs", m=1, k=2) +
                      s(AOP, Speaker, bs="fs", m=1, k=9), 
                    data = reg_dat_target, method = "ML", 
                    rho=rA, AR.start=reg_dat_target$start.event)

PAQ.gamm.target <- compareML(PAQ.gamm.1_T, PAQ.gamm.0_T)
PAQ.gamm.T <- PAQ.gamm.target$table

PAQ.gamm.T_summ <- summary(PAQ.gamm.1_T)

```

```{r GAMM data type PAT, message=FALSE, warning=FALSE, include=FALSE}

DT.gamm.base <- bam(PAT_scaled ~ data_type +
                       corpus +
                       category +
                       s(freq_scaled, bs = "cr") + 
                       s(length_scaled, bs = "cr") +
                       s(tokens_scaled, bs = "cr") + 
                       s(vocab_scaled, bs = "cr") +
                       s(PAQ_scaled_target, bs = "cr") +
                       s(AOP, bs = "cr") +   
                       s(AOP, by = data_type) + 
                       ti(AOP, PAQ_vocab_scaled) +
                       ti(AOP, freq_scaled) + 
                       ti(AOP, length_scaled) +
                       ti(AOP, tokens_scaled) +
                       ti(AOP, vocab_scaled) +
                       s(AOP, by=data_type, bs="cr") +
                       s(AOP, by=Speaker, bs="cr") +
                       s(AOP, by=corpus, bs="cr"),
                     dat=reg_data, method="ML")

rDT <- start_value_rho(DT.gamm.base) 
#summary(DT.gamm.1)

DT.gamm.1 <- bam(PAT_scaled ~ data_type +
                       corpus +
                       category +
                       s(freq_scaled, bs = "cr") + 
                       s(length_scaled, bs = "cr") +
                       s(tokens_scaled, bs = "cr") + 
                       s(vocab_scaled, bs = "cr") +
                       s(PAQ_scaled_target, bs = "cr") +
                       s(AOP, bs = "cr") +    
                       s(AOP, by = data_type) +                       
                       ti(AOP, PAQ_vocab_scaled) +
                       ti(AOP, freq_scaled) + 
                       ti(AOP, length_scaled) +
                       ti(AOP, tokens_scaled) +
                       ti(AOP, vocab_scaled) +
                       s(AOP, corpus, bs="fs", m=1, k=2) +
                       s(AOP, data_type, bs="fs", m=1, k=2) +
                       s(AOP, Speaker, bs="fs", m=1, k=9),  
                       dat=reg_data, method="ML",
                        rho=rDT, AR.start=reg_data$start.event)

DT.gamm.0 <- bam(PAT_scaled ~ #data_type +
                       corpus +
                       category +
                       s(freq_scaled, bs = "cr") + 
                       s(length_scaled, bs = "cr") +
                       s(tokens_scaled, bs = "cr") + 
                       s(vocab_scaled, bs = "cr") +
                       s(PAQ_scaled_target, bs = "cr") +
                       s(AOP, bs = "cr") +   
                       #s(AOP, by = data_type) + 
                       ti(AOP, PAQ_vocab_scaled) +
                       ti(AOP, freq_scaled) + 
                       ti(AOP, length_scaled) +
                       ti(AOP, tokens_scaled) +
                       ti(AOP, vocab_scaled) +
                       s(AOP, corpus, bs="fs", m=1, k=2) +
                       #s(AOP, data_type, bs="fs", m=1, k=2) +
                       s(AOP, Speaker, bs="fs", m=1, k=9),  
                       dat=reg_data, method="ML",
                        rho=rDT, AR.start=reg_data$start.event)


gamm.data.type <- compareML(DT.gamm.1, DT.gamm.0)
gamm.DT <- gamm.data.type$table

DT.gamm.summ <- summary(DT.gamm.1)
Estimate_DT <- as.data.frame(DT.gamm.summ$p.coeff) %>%
  rownames_to_column() %>%
  filter(rowname == "data_typetarget") %>%
  dplyr::select(-rowname)

Estimate_DT <- as.numeric(Estimate_DT)

p_DT <- as.data.frame(DT.gamm.summ$p.pv) %>%
  rownames_to_column() %>%
  filter(rowname == "data_typetarget") %>%
  dplyr::select(-rowname)

p_DT <- as.numeric(p_DT)
```

```{r GAMM output table, echo=FALSE, message=FALSE, warning=FALSE}

gamm.models.A <- rbind(PAT.gamm.A, PAQ.gamm.A, gamm.DT) 
dummy.T <- PAT.gamm.T %>%
  mutate(Model = "DT.gamm.0", Score = "", Edf = "", Difference = "",
                                                          Df = "", p.value = "", Sig. = "")
gamm.models.T <- rbind(PAT.gamm.T, PAQ.gamm.T, dummy.T) 
gamm.models.all <- cbind(gamm.models.A, gamm.models.T)
gamm.models.all <- gamm.models.all[,-8]
gamm.models.all <- gamm.models.all %>%
  mutate(Model = fct_recode(Model,
                            "PAT:Age" = "PAT.gamm.1_A",
                             "PAQ:Age" = "PAQ.gamm.1_A",
                            "PAT:Data type" = "DT.gamm.1"),
         p.value = ifelse(Sig. == "***", "<.001", p.value),
         p.value.1 = ifelse(Sig..1 == "***", "<.001", p.value.1)) %>%
  filter(Difference > 0 | Difference.1 > 0) %>%
  rename("Chi Sq" = "Difference",
         "Chi Sq.1" = "Difference.1",
         "p" = "p.value",
         "p.1" = "p.value.1") %>%
  mutate(".1" = row_number()) %>%
  dplyr::select(`.1`, Model, Df, `Chi Sq`, p, Df.1, `Chi Sq.1`, p.1)

```

```{r table-GAMM-outputs, echo=FALSE, message=FALSE, warning=FALSE}
cap="Outputs from nested model comparisons of GAMMs testing the effect of age on weighted PAT and PAQ values in Actual and Target data (Models 1 and 2), and the effect of Data type on PAT values (Model 3)."
kable(gamm.models.all, "latex", booktabs=T, longtable=T, caption=cap, digits=2, align="c",
      col.names=c(" ", "Model", "Df", "Chi Sq", "p", "Df", "Chi Sq", "p")) %>%
    kable_styling()%>%
  add_header_above(c(" "=2, "Actual"=3, "Target"=3))
```

```{r figure-GAMM-PAT, echo=FALSE, fig.cap=cap, fig.pos='H', message=FALSE, warning=FALSE,results='hide',fig.keep='all'}

{plot_smooth(PAT.gamm.1_A, view="AOP", rug=F, col="red",  
              ylim = c(-2,3),
              xlim = c(12,30),
              #main = "A: PAT, Actual data",
              xlab = "Age (months)",
              ylab = "PAT value (scaled)",
              hide.label = T)
plot_smooth(PAT.gamm.1_T, view="AOP", rug=F, col="blue", add=T, 
              ylim = c(-2,3),
              xlim = c(12,30),
              #main = "B: PAT, Target data",
              xlab = "Age (months)",
              ylab = "PAT value (scaled)",
              hide.label = T)}

cap <- sprintf("PAT values over time in Actual and Target data, weighted according to accumulative vocabulary size. Red line represents Actual values, blue line represents Target values; coloured bands represent 95%% CIs.")
```

```{r figure-GAMM-PAQ, echo=FALSE, fig.cap=cap, fig.pos='H', message=FALSE, warning=FALSE,results='hide',fig.keep='all'}

{plot_smooth(PAQ.gamm.1_A, view="AOP", rug=F, col="red",  
              ylim = c(-1,0.5),
              xlim = c(12,30),
              #main = "A: PAT, Actual data",
              xlab = "Age (months)",
              ylab = "PAQ values (scaled)",
              hide.label = T)
plot_smooth(PAQ.gamm.1_T, view="AOP", rug=F, col="blue", add=T, 
              ylim = c(-1,0.5),
              xlim = c(12,30),
              #main = "B: PAT, Target data",
              xlab = "Age (months)",
              ylab = "PAQ values (scaled)",
              hide.label = T)}

cap <- sprintf("PAQ values over time in Actual and Target data, weighted according to accumulative vocabulary size. Red line represents Actual values, blue line represents Target values; coloured bands represent 95%% CIs. Both smooths are shown here for exploratory purposes.")
```

### Data type comparisons


```{r difference-smooth-data-type, echo=FALSE, fig.cap=cap, fig.pos='H', message=FALSE, warning=FALSE,results='hide',fig.keep='all'}

plot_diff(DT.gamm.1, view="AOP", comp=list(data_type=c("target","actual")),
  main = "",
  ylab = "Est. difference in scaled PAT values",
  xlab = "Age (months)",
  xlim = c(10,30),
  hide.label = TRUE)

cap <- sprintf("Difference smooth plot showing difference between scaled PAT values in Actual vs. Target forms from the GAMM model specified above. Shaded area shows 95%% confidence intervals, red line along x-axis indicates months in which
the difference between Actual and Target forms was significant.")
```


```{r plotted-smooth-data-type, echo=FALSE, fig.cap=cap, fig.pos='H', message=FALSE, warning=FALSE,results='hide',fig.keep='all'}

data_type_plot
cap <- sprintf("Smooth plot showing scaled PAT values in Actual vs. Target forms. Shaded areas show 95%% confidence intervals, lines indicate mean trajectories over time, coloured circles represent individual datapoints, jittered for visual clarity.")
```

\newpage

# References
```{r create_r-references}
r_refs(file="r-references.bib")
```

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id="refs"></div>
\end{longtable}
\endgroup
